references:
  commands:
    sam_deploy: &sam_deploy
      name: AWS SAM DEPLOY
      command: |
        npm run config -- --account-id="$AWS_ACCOUNT_ID" --bucket-name="$SERVERLESS_EXPLESS_BUCKET" --region="$AWS_REGION"
        cat package.json

version: 2

jobs:
  build_job:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  deploy_job:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Install aws-cli
          command: |
            pip install --upgrade pip
            pip install awscli aws-sam-cli
      - run: sam --version
      - run: *sam_deploy

workflows:
  version: 2
  build_deploy_flow:
    jobs:
      - build_job
      - deploy_job:
          requires:
            - build_job
          filters:
            branches:
              only:
                - master
